/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import java.util.List;

public class App {

    public static void main(String[] args) {
      makeGraph();
    }

    public static Graph makeGraph(){
      Graph graph = new Graph();

      graph.addNode(4);
      graph.addNode(3);
      graph.addNode(8);
      graph.addNode(10);
      graph.addNode(420);

      graph.addEdge(4,3);
      graph.addEdge(3,8);
      graph.addEdge(3,420);
      graph.addEdge(10,420);

      List<Graph.Node> nextTo = graph.getAdjacentNodes(3);

      System.out.println(graph);
      System.out.println();
      return graph;
    }
}
