/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist.fromtail;

import java.util.LinkedList;

public class Library {



    public int findValueFromTail(int key) {
      LinkyLIst list = new LinkyLIst();
      list.insert(list,1);
      list.insert(list,2);
      list.insert(list,4);
      list.insert(list,5);
      list.insert(list,9);


        int count = 0;
        int solution = 0;

        while(list.head.next != null){
          count ++;
        }

        int position = count - key;

        for(int i = 0; i >= position; i++){
          if(i == position){
            solution = list.head.data;
            break;
          }
        }

        return solution;
    }
}
