/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.ques;

import org.junit.jupiter.api.Test;
import psuedoque.Psuedoque;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test void PushNodeToStack() {
        Stack sut = new Stack();
        sut.push(1);
        sut.push(2);
        sut.push(3);
        sut.push(4);

        Integer expected = 4;

        assertEquals(expected, sut.push(4));
    }

  @Test void PopNodeStack(){
    Stack sut = new Stack();

    sut.push(3);
    Node expected= new Node();
    expected.data = 3;
    assertNotNull(sut.pop());
  }

  @Test void PeekNodeStack(){
      Stack sut = new Stack();

  }

  @Test void Empty(){
      Stack sut = new Stack();
      assertTrue(sut.isEmpty());
  }

  @Test void EnqueueCheckForEnd(){
      Que sut = new Que();
      Integer expected = 4;
      assertEquals(expected, sut.enqueue(4));
  }

  @Test void Dequeue(){
      Que sut = new Que();
      Node expected = new Node();
      sut.front.data = 3;
      expected.data = 3;
      assertNotNull(sut.dequeue());
  }

  @Test void PeekChecker(){
      Que sut = new Que();
      assertNotNull(sut.peek());
  }

  @Test void IsEmptyChecker(){
      Que sut = new Que();
      assertTrue(sut.isEmpty());
  }

  @Test void PsuedoEnque(){
    Psuedoque sut = new Psuedoque();
    sut.enqueue(4);

    int expected = 4;
    assertEquals(expected, sut.inbox);
  }

  @Test void PsuedoDeque(){
      Psuedoque sut = new Psuedoque();
      sut.enqueue(3);
      sut.enqueue(2);
      sut.enqueue(1);

      sut.dequeue();

      int expected = 1;

      assertEquals(expected, sut.outbox.pop());
  }
}
