/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap;

import java.awt.*;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    String str = "Once upon a time, there was a brave princess who...";

    Map<String, Integer> hashMap = new HashMap<>();
    String[] words = str.split(" ");
    String key = null;

    for (String word : words) {

      if (hashMap.containsKey(word)) {
        hashMap.put(word, hashMap.get(word) + 1);
      } else {
        hashMap.put(word, 1);
      }

      key = Collections.max(hashMap.entrySet(), Map.Entry.comparingByValue()).getKey();
    }

    System.out.println(key);
  }

}
