/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.insertion;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void canAppend() {
        LinkyList sut = new LinkyList();
        sut.appendNumerical(1);
        sut.appendNumerical(2);
        sut.appendNumerical(3);
        sut.appendNumerical(4);

        ArrayList<Integer> expected = new ArrayList<>();
        expected.add(1);
        expected.add(2);
        expected.add(3);
        expected.add(4);

        assertEquals(expected, sut.list);
    }

    @Test void addBefore(){
      LinkyList sut = new LinkyList();
      ArrayList<Integer> test = new ArrayList<>();
      sut.appendNumerical(1);
      sut.appendNumerical(2);
      sut.appendNumerical(3);
      sut.appendNumerical(5);
      sut.appendNumerical(6);



        ArrayList<Integer> Junk= sut.insertBefore(5,4);

      ArrayList<Integer> expected = new ArrayList<>();
      expected.add(1);
      expected.add(2);
      expected.add(3);
      expected.add(4);
      expected.add(5);
      expected.add(6);

      assertEquals(expected, Junk);
    }

  @Test void addAfter(){
    LinkyList sut = new LinkyList();
    ArrayList<Integer> test = new ArrayList<>();
    sut.appendNumerical(1);
    sut.appendNumerical(2);
    sut.appendNumerical(3);
    sut.appendNumerical(5);
    sut.appendNumerical(6);




    ArrayList<Integer> Junk= sut.insertAfter(3,4);

    ArrayList<Integer> expected = new ArrayList<>();
    expected.add(1);
    expected.add(2);
    expected.add(3);
    expected.add(4);
    expected.add(5);
    expected.add(6);

    assertEquals(expected, Junk);
  }
}
